name: release circom binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo test --verbose
    - name: Compile
      id: compile
      run: cargo build --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: circom
        path: |
          mkdocs/docs/binaries/ubuntu/${{ steps.compile.outputs.BUILT_ARCHIVE }}
          mkdocs/docs/binaries/ubuntu/${{ steps.compile.outputs.BUILT_CHECKSUM }}
