name: release circom binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Compile
      id: compile
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: circom
        path: |
          /home/runner/work/circom/circom/target/release/circom
